import React, { Fragment } from 'react'
import dog from '../assets/images/dog.png'

const About = () => (
  <Fragment>
    <h1>LAB 7 - CARLOS CHEW</h1>
    <h2>Historia de como me perdi en Asia, PARTE 4-6</h2>
    <p>(PARTE 4) Llegamos el día viernes por la noche, como a las 11, por lo que ningun lugar turistico estaba abierto, por lo cual decidimos solamente ir a cenar, que mejor que ir a In N Out, yo pedí un double double, sinceramente creo que es la hamburguesa más rica que he probado en mi vida, simplemente espectacular. El siguiente día era el día de salir a conocer, desayunamos en la casa en la cual nos estabamos quedando, luego fuimos al Santan Monica Pier, lugar bonito, playa bonita, literalmente como el área de GTA 5, exactamente lo mismo, bonitos souvenirs. Luego fuimos al downtown. Al walk of fame, a ver el signo de hollywood y al teatro chino. La verdad no fue una experiencia muy agradable, mucho tráfico, mucha gente sin casa, mucho olor a desechos humanos y a drogas, en medio del lugar turístico. Luego fuimos a comer a un restaurante mexicano, churrasco y tortillas, muy rico la verdad, pero nada del otro mundo. Y la última actividad del día fue ir a un outlet para comprar unas cositas ya que en Guatemala no hay nada. Pasamos como 6 horas dando vueltas, hasta que ya habíamos visto todo. Decidimos irnos, ya era noche, pasamos comprando comida china tipo panda express, para llegar hacer las maletas y hacer el check in. Como conclusión LA no lo recomiendo, nada del otro mundo. En lo personal no volvería a ir. El día siguiente fuimos al aereopuerto para irnos a Japón. </p>
    <p>(PARTE 5) Decidimos ir a Japón porque sabiamos que había buena comida y bonita arquitectura. De LA a Japón era un vuelo largo, por lo que saiamos que nos teníamos que entretenes, cuando pasaron la primer comida empezamos a tomar alcohol, lo cual nuestra intención era relajarnos y dormirnos comodos, pero nos pasamos de unos traguitos. Despues de un vuelo largo, finalmente llegamos, al bajarnos del avión el personal nos saluda con cierta reverencia, un choque cultural enorme, pero muy fascinados de ver como ellos expresan el respeto. Nuestro hotel quedaba en ginza, el cual era e l downtown, nos subimos al bus que habíamos reservado y nos llevó a una estación que estaba relativamente cerca del hotel, lo único malo es que estaba lloviendo, nosotros con las grandes maletas, con jetlag, y cansados tuvimos que correr al hotel. Finalmente llegamos, un hotel pequeño, de talvez 5 niveles, y los cuartos eran dobles. Nunca en mi vida había estado en un cuarto tan pequeño, era impresionantemente pequeño, pero era parte de la experiencia. Apenas había espacio para caminar, y el baño ni digamos, el lavamanos y la bañera era uno solo para maximizar el espacio. El día que llegamos solamente fuimos a cenar, y luego a descansar. Al otro día fuimos a un parque tipo vivero, en medio de la ciudad, espectularmente bonito, muy relajante. Luego fuimos a shibuya, la calle peatonal más congestionada del mundo, es la calle de Tokyo Drift donde tocan la bocina para que se muevan, muy bonito la verdad, nos sentamos en un starbucks para comer la refa y ver el paisaje. Luego fuimos a un templo para conocer su cultura, para despues ir a almorzar, unos tempura. Simplemente espectular. Toda la ciudad muy limpia, ordenado y automatizado. Caminamos un montón, siempre nos movimos en el metro. A la hora de la cena regresamos al hotel para cambiarnos e irnos a buscar que comer, se nos ocurrió ir a McDonals, espectaular, en mi opinión Mc nunca te va a fallar. Y eso fue todo. En conclusión regresaría a Japón, incluso podría vivir ahí. </p>
    <p>(PARTE 6) Esta parte será devidida, ya que estuvimos muchos días. Llegamos a Hong Kong, sabiamos desde un principio que sería una ciudad cara, por gran desarrollo económico pero sabíamos que valía la pena. Al llegar al aereopuerto pedimos un Uber, para llegar al hotel, al ver mi celular me notificó que llegaría un Tesla, muy emocionado ya que nunca me había subido a un carro de esos. Pero preocupados ya que en Hong Kong la gente ya estaba protestando al gobierno por el abuso de autoridad, sin embargo, el chofer decidió una vía alterna para no hacer tráfico. Finalmente llegamos al hotel para hacer check in y alistarnos para ir a comer. Al tener la oportunidad de estar en una gran ciudad decidimos ir a comer a un restaurante con estrellas Michellin de Dim Sun, espectacular la comida. Aclaro que si alguien es melindroso no le gustaría pero a mi grupo de amigos quedamos totalmente fascinados. Eso fue en el almuerzo, para la tarde fuimos a un mercado de noche, a comprar recuerdos y diferentes cositas. El mercado enorme, mucha gente y muy alegre. Es fue nuestro primer día. </p>
  </Fragment>
)
export default About
